name: 'Terraform GHA'
on:
  push:
    branches:
      - '*'
      - '!main'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Plan
        run: echo "Plan"
  
  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: env
    steps:
      - name: Apply
        run: echo "Auto Apply"      
