name: 'Terraform GHA'
on:
  push:
    branches:
      - '*'
      - '!main'
    
  pull_request:
    branches:
      - '*'
      - '!main'
    types: [opened, synchronize, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
  plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Plan
        run: echo "Plan!"
  
  apply:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
#     if: github.event_name == 'pull_request' && github.event.pull_request.merged == false
    steps:
      - name: Apply
        run: echo "Auto Apply"      
