name: 'Terraform GHA'
on:
  push:
    branches:
      - '*'
      - '!main'
    
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
#       - name: Terraform Format
#         id: fmt
#         run: terraform fmt -check
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Plan
        id: plan
        run: terraform plan
  
  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: env
    steps:
      - name: Apply
        run: terraform apply -auto-approve
