name: 'Terraform GHA'
on:
  push:
    branches:
      - '*'
      - '!main'
    
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create folder for plan
        run: mkdir plan
                    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate -no-color
      
      - name: Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -out ./plan/tfplan
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: plan
  
  apply:
    runs-on: ubuntu-latest
    needs: plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    environment: env
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
            
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate -no-color
        
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          
      - name: check folder
        run: ls
        
      - name: Unzip artifact
        run: unzip -o /home/runner/work/gha/gha/tfplan -d /home/runner/work/gha/gha/tfplan/tfplan

      - name: Apply
        run: terraform apply /home/runner/work/gha/gha/tfplan/tfplan/tfplan
            #-auto-approve
