name: 'Terraform GHA1'
on:
  push:
    branches:
      - '*'
      - '!main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_BUCKET: sk-terraform-2022-state-backend
  AWS_BUCKET_KEY: tfstate
  AWS_REGION: us-east-1
  AWS_DYNAMODB_TABLE: tf-state-236117720236-us-east-1
  TERRAFORM_VERSION: 1.2.7

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
                   
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      
      - name: Terraform Init          
        run: terraform init -backend-config=client_id=$AWS_ACCESS_KEY_ID -backend-config=client_secret=$AWS_SECRET_ACCESS_KEY -backend-config=aws_region=$AWS_REGION -backend-config=dynamodb_table=$AWS_DYNAMODB_TABLE
#         run: terraform init -backend-config=bucket_name=$AWS_BUCKET -backend-config=key=$AWS_BUCKET_KEY -backend-config=client_id=$AWS_ACCESS_KEY_ID -backend-config=client_secret=$AWS_SECRET_ACCESS_KEY
      
      - name: Terraform Validate
        run: terraform validate -no-color
      
      - name: Plan
        run: terraform plan -out tfplan
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          path: tfplan
          retention-days: 7 #by default 90 days
  
  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: env
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
            
      - name: Terraform Init
        run: terraform init -backend-config=client_id=$AWS_ACCESS_KEY_ID -backend-config=client_secret=$AWS_SECRET_ACCESS_KEY -backend-config=aws_region=$AWS_REGION -backend-config=dynamodb_table=$AWS_DYNAMODB_TABLE
      
      - name: Terraform Validate
        run: terraform validate -no-color
        
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: tf-plan
          path: tfplan
                 
      - name: Apply
        run: terraform apply tfplan/tfplan
