name: 'Terraform GHA'
on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
  plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Plan
        run: echo "Hello World!!"
  
  apply:
    runs-on: ubuntu-latest
   # needs: plan
    if: github.event_name == 'pull_request'
    steps:
      - name: Apply
        run: echo "Auto Apply"
      
